from lib.pairs import Pair
from lib.pairs import pairs
TG_ENABLED=True
TG_VERBOSE="Full"
GUNBOT_CONFIG_FILE="config.js"
GUNBOT_JSON_DIR="json"
LOG_FILE="logging.txt"
CHECK_DELAY = 5
STAT_MSG_TIMEOUT = 15
UV_FILE = "USR_VARS.ini"
ISL = False
ISL_LIMIT = 20
LIQ = True
BINANCE = True
BIN_PATH = "None"
OLD_ROE_CALC = False
USDTBTC = Pair("USDT-BTC")
USDTBTC.settings.MAX_BUY=5 
USDTBTC.settings.MAX_SELL=5 
USDTBTC.settings.TRADING_LIMIT=50 
USDTBTC.settings.MAX_OPEN_CONTRACTS=10000000 
USDTBTC.settings.LIQUIDATION_LIMIT=30 
USDTBTC.settings.PRICE_DELTA_LIMIT=0.4 
USDTBTC.settings.DELAY_HIGH = 6 
USDTBTC.settings.DELAY_LOW = 0 
USDTBTC.settings.PDP_VOL_FAST = 200 
USDTBTC.settings.PDP_VOL_SLOW = 200 
USDTBTC.settings.ROE_LIMIT = 1
USDTBTC.settings.PDP_NO_ROE_CLOSE = True 
USDTBTC.settings.TL_AC = True
USDTBTC.settings.TLX = 6
USDTBTC.config.ROE_TRAILING = True 
USDTBTC.config.MARKET_CLOSE = True 
USDTBTC.settings.NO_MARKET_ORDERS = False 
USDTBTC.settings.SR_SWITCH = False
USDTBTC.settings.TT_LOCK = 10
USDTBTC.settings.UNLIM_ROE_LOW = -15
USDTBTC.settings.ROE = 15
USDTBTC.settings.GRID = True
USDTBTC.settings.NO_SIDE_LOCK = True
USDTBTC.settings.DCA_EMA = False
USDTBTC.settings.x125 = False
USDTBTC.settings.STATS_DTIME = 24
USDTBTC.settings.NO_STUCK = False
USDTBTC.settings.GRID_FORCE = True
USDTBTC.settings.STOP_LOSS = False
USDTBTC.settings.SL_LIMIT = 0.5
USDTBTC.settings.SL_LL = True
USDTBTC.settings.SPK = False
pairs.append(USDTBTC)
